@url = http://localhost:5000

@reservationId = 00000000-0000-0000-0000-000000000001

@parkingSpotId = 00000000-0000-0000-0000-000000000001


###
GET {{url}}/reservations


###
GET {{url}}/reservations/{{reservationId}}


###
POST {{url}}/reservations/vehicle
Content-Type: application/json

{
    "ParkingSpotId": "00000000-0000-0000-0000-000000000001",
    "EmployeeName": "John Doe",
    "LicensePlate": "XYZ123",
    "date": "2022-08-14"

}

###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
    "date": "2022-08-14"
}